{% set name = "apipkg" %}
{% set version = "3.0.1" %}
{% set hash = "f8c021adafc9132ac2fba9fd3c5768365d0a8c10aa375fb15e329f1fce8a5f01" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatch-vcs
    - hatchling >=0.24
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - apipkg

about:
  home: https://github.com/pytest-dev/apipkg
  dev_url: https://github.com/pytest-dev/apipkg
  license: MIT
  license_file: LICENSE
  summary: With apipkg you can control the exported namespace of a python package and greatly reduce the number of imports for your users.

extra:
  recipe-maintainers:
    - nicoddemus
