{% set name = "apipkg" %}
{% set version = "3.0.2" %}
{% set hash = "c7aa61a4f82697fdaa667e70af1505acf1f7428b1c27b891d204ba7a8a3c5e0d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatch-vcs
    - hatchling >=0.24
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - apipkg

about:
  home: https://github.com/pytest-dev/apipkg
  dev_url: https://github.com/pytest-dev/apipkg
  license: MIT
  license_file: LICENSE
  summary: With apipkg you can control the exported namespace of a python package and greatly reduce the number of imports for your users.

extra:
  recipe-maintainers:
    - nicoddemus
